# -*- coding: utf-8 -*-
"""21341015_ArnabSaha_A1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFYj4slzVxXyQJ25UMUx47N6wkh1rsGH

Part 1
"""

import heapq

def Manhattan_distance(p1,p2):
  x = p1[0]-p2[0]
  y = p1[1]-p2[1]
  return abs(x+y)

def A_star(maze, start, goal, n, m):
  directions = [(-1, 0, 'U'), (1, 0, 'D'), (0, -1, 'L'), (0, 1, 'R')]

  visited_node=[]
  for i in range (n):
    row=[]
    for j in range (m):
      row.append(False)
    visited_node.append(row)
  queue1=[]
  heapq.heappush(queue1, (Manhattan_distance(start,goal), 0, start, ""))
  while queue1:
        f, g, (x, y), path = heapq.heappop(queue1)

        if (x, y) == goal:
            print(g)
            print(path)
            return

        if visited_node[x][y]:
            continue
        visited_node[x][y] = True

        for dx, dy, move in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < m and maze[nx][ny] == '0' and not visited_node[nx][ny]:
                new_g = g + 1
                new_h = Manhattan_distance((nx, ny), goal)
                heapq.heappush(queue1, (new_g + new_h, new_g, (nx, ny), path + move))

  print(-1)

n, m = map(int, input().split())
a, b = map(int, input().split())
c, d = map(int, input().split())

maze = []
for _ in range(n):
    maze.append(list(input().strip()))

A_star(maze, (a, b), (c, d), n, m)

"""Part 2"""

from collections import deque

def admissible_check(n, m, start, goal, heuristic_values, edges):
    graph = [[] for _ in range(n + 1)]
    for u, v in edges:
        graph[u].append(v)
        graph[v].append(u)

    distance = [float('inf')] * (n + 1)
    queue = deque()
    queue.append(goal)
    distance[goal] = 0

    while queue:
        node = queue.popleft()
        for neighbor in graph[node]:
            if distance[neighbor] == float('inf'):
                distance[neighbor] = distance[node] + 1
                queue.append(neighbor)

    not_admissible = []
    for node in range(1, n + 1):
        if heuristic_values[node] > distance[node]:
            not_admissible.append(node)

    if not not_admissible:
        print(1)
    else:
        print(0)
        print(*not_admissible)

n, m = map(int, input().split())
start, goal = map(int, input().split())

heuristic_values = [0] * (n + 1)
for _ in range(n):
    node, h = map(int, input().split())
    heuristic_values[node] = h

edges = []
for _ in range(m):
    u, v = map(int, input().split())
    edges.append((u, v))


admissible_check(n, m, start, goal, heuristic_values, edges)